### ISSUE TITLE
Error on parsing aff and skl folder

### ISSUE THREAD

**Issue by nick535897** [mfloob/diablo4-data-harvest#3]
PS C:\Users\Nick\OneDrive\文档\GitHub\diablo4-data-harvest> cargo run
warning: `C:\Users\Nick\.cargo\config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: unused variable: `data`
  --> src\app.rs:34:20
   |
34 |         let Self { data } = self;
   |                    ^^^^ help: try ignoring the field: `data: _`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `diablo4-data-harvest` (bin "diablo4-data-harvest") generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.26s
     Running `target\debug\diablo4-data-harvest.exe`
thread 'main' panicked at src\app.rs:50:61:
called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\diablo4-data-harvest.exe` (exit code: 101)

PS C:\Users\Nick\OneDrive\文档\GitHub\diablo4-data-harvest> cargo run
warning: `C:\Users\Nick\.cargo\config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: unused variable: `data`
  --> src\app.rs:34:20
   |
34 |         let Self { data } = self;
   |                    ^^^^ help: try ignoring the field: `data: _`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `diablo4-data-harvest` (bin "diablo4-data-harvest") generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.29s
     Running `target\debug\diablo4-data-harvest.exe`
thread 'main' panicked at src\parsers\skl.rs:57:33:
attempt to add with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\diablo4-data-harvest.exe` (exit code: 101)

**Comment by mfloob** [comment]
I'm sure they updated the structure of their data files by now. You'll have to reverse it.
